# Generated by Django 4.1.7 on 2023-04-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceitaIngrediente',
            new_name='RecipeIngridient',
        ),
    ]
