# Generated by Django 4.1.7 on 2023-04-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopia', '0002_rename_recipeingridient_recipeingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe_id', 'ingredient_id')},
        ),
    ]
