# Generated by Django 4.1.7 on 2023-04-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopia', '0003_rename_ingredient_recipeingredient_ingredient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
