# Generated by Django 4.1.7 on 2023-04-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopia', '0005_recipesteps_recipe_recipesteps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeSteps',
        ),
        migrations.AddField(
            model_name='recipesteps',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooktopia.recipe'),
        ),
    ]
