# Generated by Django 4.1.7 on 2023-04-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopia', '0010_remove_chef_followers_cheffollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='country',
            field=models.CharField(default='portugal', max_length=30),
            preserve_default=False,
        ),
    ]
