# Generated by Django 4.1.7 on 2023-04-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopia', '0011_chef_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cooktopia.recipe'),
        ),
    ]
