# Generated by Django 4.1.7 on 2023-05-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopia', '0012_userhelp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cooktopia.recipe'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooktopia.chef'),
        ),
    ]
